version: "3.8"
services:
  dev:
    image: #docker image (e.g., node:latest)
    stdin_open: true
    tty: true
    container_name: dev-container
    volumes:
      - type: bind
        source: ../
        target: /home/dev
    ports:
      - target: 8080
        published: "8080"
        host_ip: 127.0.0.1
        protocol: tcp
    networks:
      - devnet

networks:
  devnet:
    name: devnet
